# Generated by Django 5.0 on 2023-12-31 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_blogpost_delete_goods_alter_comment_post_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
